### ISSUE TITLE
Difference in performance?

### ISSUE THREAD

**Issue by lunks** [leoasis/graphql-tag.macro#1]
Is there some data on how performance is changed with this?

**Comment by joshribakoff** [comment]
If you're parsing an AST you avoid the parsing cost, but you may ship more bytes because the AST is more verbose than the string but in exchange you avoid having to ship a runtime parser.

It depends.

**Comment by leoasis** [comment]
@joshribakoff answered it, parsing has a cost that may not be small if you have lots of queries, especially if they are all defined at the root level of modules, which is usually the case. Also you don't need to ship the parser, which saves some bytes as well. 

Having said that, you should always measure yourself before applying any optimization, to see if there's a real gain, both in bundle size and in runtime perf. 

The good thing is that this library should be a drop in replacement that just requires you to change the name of the imported module and everything should work the same way.

**Comment by leoasis** [comment]
Feel free to reopen and/or continue the discussion if you think your question was unanswered!
