### ISSUE TITLE
 Could not find a declaration file for module 'graphql-tag.macro'. 

### ISSUE THREAD

**Issue by ibigpapa** [leoasis/graphql-tag.macro#6]
Add Type definition for graphql-tag.macro?

https://github.com/leoasis/graphql-tag.macro/pull/5

**Comment by zackify** [comment]
This has been done

**Comment by patricknick** [comment]
Shouldn't the index.d.ts be included in the package that gets published to NPM? In v2.1.0, the package only includes the index.js without typings.
